language: ruby
sudo: false
cache: bundler
bundler_args: --without production
before_install:
  - gpg -d -o config/application.yml config/application.yml.asc
rvm:
  - 2.2.2
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
script:
  - cp config/database.yml.test config/database.yml
  - bundle exec rake db:setup
  - bundle exec cucumber
  - bundle exec rake spec
after_script:
  - rm -f config/application.yml
