language: ruby
rvm:
- 2.5.5
sudo: false
cache: bundler
bundler_args: "--without production"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - CC_TEST_REPORTER_ID=c2b95b25d30ce5fa83d28309f1857d559be106347c00705aeb5325bc10c46935
  - CCTR=/tmp/cc-test-reporter
  - secure: hdRn32hNPSTwivw6+iZsZ5beeNVnbWVlWWrA+uAPgUBTkmBELAQyb0E79DRk93xpm9dluIkR2fqAC9s6lNQY6beOGumuq7XRaWYr83ILGZAAS8FK3uLlrT6a7uhh9zFaIqn676EYXnGgP43sAmnIm4cguSK6zwo0n+UHNrx95pS6G0QiuNc30dgj/AQdAhRIqMNrvAJQ6OS/mn39V/A+g60pR3COoG3ToweU+ivzoF91E0hhiBl9+vlMN9EKoxuqCzUjktqoFfwAagc1zMq+je8RW4UDDnk4K+p5d7TWEqrmUJdvTWIub5uirpHSm2GQySTlCcLQD8ypXwLyMIhKHydaCEUXgzh48O5KOIHoX9hf1RQdOvxuy8F3FKk8yojuAxx/VvSLjj2wJm/IDEe//h3YUSh6XAWlCp8S0E1jAOAJnDS/Uz6pysvGNOjKDt4ToHAxQvoSzfz3/7/EBWAY0UGScRc6C4/iTfVZ5he4j9QXf5FEOg5jPv0YbLJ5PlwbRupsBfxoHYNM+7TT9hturM8qr4yTmrZSAo5kydiZDwO2oeFhGNORJe9+c5ElbOUIseQQvp0rpntgK+GBxVIPMoqU3oAkdM+DoNSbdcSNAiPHahxAf0Vev65C6Y/62THVxhh+q+GXuvurXicX6G4PkA6bLV0NCDzZ/3S2Da/Xh+M=
before_install:
- export TZ=America/Los_Angeles
- gpg --passphrase $KEY -d -o config/application.yml config/application.yml.asc
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > $CCTR
- chmod +x $CCTR
- "$CCTR before-build"
- gem install bundler --version=1.17.2
- bundle config build.nokogiri --use-system-libraries
script:
- cp config/database.yml.test config/database.yml
- bundle exec rake db:setup
- bundle exec cucumber --retry 1
- "$CCTR format-coverage --output coverage/codeclimate.$SUITE.json"
- bundle exec rspec
- "$CCTR format-coverage --output coverage/codeclimate.$SUITE.json"
after_script:
- "$CCTR sum-coverage coverage/codeclimate.*.json | $CCTR upload-coverage"
- "$CCTR after-build --exit-code $TRAVIS_TEST_RESULT"
- rm -f config/application.yml
