language: ruby
sudo: false
cache: bundler
rvm:
  - 2.3.1
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
script:
  - cp config/database.yml.test config/database.yml
  - bundle exec rake db:setup
  - bundle exec cucumber
  - bundle exec rake spec
