<%
format = '--require features --format pretty --color'
%>
autotest: <%= format %> --tags @wip 
default: <%= format %> --tags ~@facebook
javascript: <%= format %> --tags @javascript
passing:  <%= format %> --tags ~@wip  
cur:  --tags @cur <%= format %>
