<%
format = '--require features --format pretty --color'
%>
autotest: <%= format %> --tags @ip 
default: <%= format %> --tags ~@selenium --tags ~@facebook
selenium: <%= format %> --tags @selenium
passing:  <%= format %> --tags ~@wip  
cur:  --tags @cur <%= format %>
