<%
format = '--require features --format pretty --format rerun --out rerun.txt --color'
%>
autotest: <%= format %> --tags @ip 
default: <%= format %> --tags ~@javascript --tags ~@facebook --tags ~@wip
javascript: <%= format %> --tags @javascript
passing:  <%= format %> --tags ~@wip  
cur:  --tags @cur <%= format %>
