<%
format = '-m -i --require features --format pretty --format rerun --out rerun.txt --color'
%>
autotest: <%= format %> --tags @wip 
default: <%= format %> --tags ~@facebook --tags ~@javascript --tags ~@wip
javascript: <%= format %> --tags @javascript
passing:  <%= format %> --tags ~@wip  
cur:  --tags @cur <%= format %>
