<%
format = '--require features --format pretty --color'
%>
default: <%= format %> 
autotest: <%= format %> --tags @ip 
selenium: <%= format %> --tags @selenium
passing:  --tags ~@wip <%= format %> 
cur:  --tags @cur <%= format %>
