# General

disable_admin: >
  
  Lets you switch between viewing the site with admin privileges vs. how
  a regular patron would see it.  

# Logging in

login_using_facebook: >

  This feature lets you use your existing Facebook username and password
  to login rather than remembering a separate username and password.  Your
  Facebook password is never revealed to us, and we only use your Facebook
  information to log you in and tell you which of your friends are
  attending shows and who has "Liked" shows.  If you already have a
  username and password with us, login with those and then click "Link
  my account to Facebook" on the welcome page after logging in.

secret_question: >

  If you set up a secret question and answer, you can use it to log in
  if you ever forget your password.

# Store pages

credit_card_verification_value: >

  The CVV (security) code is the last three digits of the
  number printed on the BACK of your card, or for AmEx, the FOUR
  digits printed in small type on the FRONT of your card.

skip_validation: >

  Checking this box, which is invisible to regular customers, skips
  certain credit card prevalidations (including CVV checking) 
  normally performed
  before submitting the charge transaction.  Check this box at
  your own risk!

# Show/showdate setup pages

advance_sales_cutoff: >

  The time after which customers cannot self-purchase tickets online for
  this performance.  (You can set a default value for this in Admin >
  Options.) 

max_advance_sales: >

  The maximum allowed advance sales/reservations for this performance,
  which may be less than the show's house capacity (specified
  as part of the overall show information).  If this number is
  zero, or is greater than the actual house capacity, the actual house
  capacity will be used.  The ticket availability shown to customers
  (when they self-purchase/reserve, or via the RSS feed) is based on
  this number, so a show whose max advance sales is 100 will report
  "sold out" when 100 tickets are sold, even if the physical house
  capacity has been set higher than 100.

# Customers and customer lists

customer_labels: >

  You can 'tag' customers with labels of your choice, such as Volunteer,
  Merchant Partner, etc.  Labels can then be used in report generation.

filter_by_zip: >

  Patterns that match the start of a zip code, separated by
  commas. '945,946'  matches anything starting with 945 or 946.  '94'
  matches anything starting with 94.  '94,925' matches anything starting
  with 94 or anything starting with 925, etc.

merge_customers: >

  To merge duplicates, select exactly 2 customer records.  Merging
  manually lets you choose which field values are retained; merging
  automatically retains all nonblank field values, breaking ties by
  preferring the customer record that has had the most recent activity.

delete_customers: > 

  When you Forget a customer, all their transactions (donations, purchases,
  etc.) are transferred to the 'Anonymous Customer', so sales reporting is
  unaffected.  If you Expunge a customer, their transactions are also
  deleted: you are re-writing history as if this customer had never
  existed, making them an un-person.  Neither action can be undone.

# Importing

import_show_name:  >
 
  Because the format of will-call lists varies, you have to specify
  which show this is for.  If it doesn't exist, enter the name of a new
  show, which will be automatically created in order to import the
  list.  NOTE!  If you enter a new show name, that show will be created 
  even if the import is aborted or fails.

import_choose_file:  >

  Each kind of import expects a specific file type and layout.  If these
  files are CSV (comma-separated values), be sure they have been saved
  as "Windows CSV".  Some imports also accept other file types.

check_for_duplicates_after_import: >
  
  When automatically importing customers (such as from an external
  will-call list or spreadsheet), Audience1st cannot always tell for
  sure if two customers with similar names are duplicates.  After doing
  any kind of import, you should check for duplicates (Reports tab, under
  Database Maintenance reports) and use your judgment in merging them.
  It's best to do duplicate elimination as soon as possible, since
  duplicate records sometimes prevent customers from being able to login.

# Bulk importing

bulk_download_login: >

  Enter the username and password you'd use to login to the "Producer"
  account for this vendor (the account that lets you download sales
  reports). 

# Editing shows and showdates

show_description: >

  You can add an optional short description to a show or event (e.g. 
  "This show contains strong language") or explanations of special
  ticket prices (e.g. "VIP Ticket price includes a free glass of wine")
  that will appear whenever the customer selects that show or event for
  ticket purchase from the Buy Tickets page.

showdate_description: >

  You can add an optional short description to a specific performance of
  a show (e.g. "Preview") that will appear next to that performance's
  date in the dropdown menu when the customer is purchasing tickets for that
  show.

show_house_capacity: >

  The true (physical) capacity of the house for this production, used
  for reporting purposes and for keeping track of how many seats are 
  available while checking in customers during Front of House
  operations.  You MUST enter a number greater than zero
  here, or all performances will appear to be sold out.
  To set the maximum allowed advance sales for a given performance, 
  click on the Edit link next to the performance date below.

show_sold_out_dropdown_message: >

  When a performance is sold out, what should appear next to the
  performance date in the dropdown menu on the ticket purchase page?  
  (Leave blank to display nothing special.)

show_sold_out_customer_info: >

  When a customer tries to select a sold-out performance on the ticket 
  purchase page, what instructions or explanation should appear?  (For 
  example, you might direct them to call the box office to inquire
  about cancellations.)

show_listing_date: >
 
  The date the show will first appear on any customer-facing screens.
  Before this date, the show will appear not to exist.

show_landing_page_url: >

  The URL of a page on your theater's Web site that has more information
  about the show.

show_is_special: >

  Indicate if this is a regular show (staged performance), special event
  that isn't really a performance (fundraiser, sponsorship opportunity,
  etc.), or an event that involves enrollment (acting class, drama camp,
  etc.)  This determines what store page the event will be listed on,
  and in some cases affects how customers purchase; for example, the
  enrollee name MUST be provided for a course enrollment.

show_also_notify: >
 
  An additional email address to notify whenever someone PURCHASES a
  ticket to this show.  (Subscriber or comp reservations do NOT result
  in an email notification.)  Note that this is in addition to the
  regular confirmation email that gets sent to the customer.  If blank,
  no separate notification will be generated.

# Vouchers and voucher types

vouchertype_display_order: >

  Controls the order in which voucher types are displayed to customers
  (on self-purchase screen).  Lower numbers appear earlier in the list.
  Numbers don't have to be consecutive, so you can add a vouchertype
  later and position it between two existing vouchertypes.  In case of a
  tie, or if you don't specify, the vouchertype created earlier appears
  earlier in the list.

vouchertype_type: >

  A Bundle is a container for a collection of vouchers (e.g. a
  subscription).  A Single Subscriber Voucher is a voucher valid for a
  particular production included as part of a subscription (although
  Bundles can contain both Single Subscriber Vouchers and comps).  All
  other types of tickets that aren't comps are Revenue Vouchers.
  Nonticket Product can be used for things like ticket exchange fees,
  ticket add-ons ("A glass of wine at intermission"), etc.

vouchertype_account_code: >

  If you use accounting software such as QuickBooks, sales of each
  voucher type can be associated with a particular account code when you
  generate reports.  If you don't use such software, you can leave this
  blank.

vouchertype_season: >

  The season during which this voucher type is valid.  The season start
  date is based on the value you provide under the Admin options.

vouchertype_availability: >

  Use "External Reseller" for tickets that will be sold through other
  channels such as TBA, Goldstar, etc.  Use "Box Office Use Only" for
  tickets that cannot be self-purchased online by customer (for example,
  special group sales).

vouchertype_fulfillment_needed: >

  If purchasing this ticket type requires physically mailing something
  to the customer (e.g., mailing a subscription package or free gift),
  check this box.  This will cause all such orders to appear in the
  "Show Orders Needing Fulfillment" report (Reports tab).

vouchertype_walkup_sale_allowed: >

  If this box is checked, this ticket type will appear on the Walk-up
  Sales screen.  Leave unchecked for any ticket types that require
  advance purchase.

vouchertype_changeable: >

  If checked, customer can change/cancel a reservation associated with
  this voucher type online WITH NO FEE.  If you want to allow
  changes/cancellations for a fee, leave this box UNCHECKED and create a
  separate Nonticket Product voucher for box office use only
  corresponding to the change fee.  (At this time, the box office must
  handle such transactions.)

vouchertype_bundle_promo_code:  >

  A promo code (password) required to purchase; this bundle type
  won't be visible as a choice in dropdown menu until customer enters the
  promo code.  To specify multiple allowable promo codes, separate them
  by commas.  If blank, no promo code is required to purchase this
  bundle. 

# Valid_vouchers

valid_voucher_max_sales_for_type:  >

  The maximum advance sales for this ticket type for this performance 
  (for per-ticket-type capacity controls).  
  A box office agent can always sell 
  beyond this limit either in advance or at walkup sales time; the limit 
  applies ONLY to customer self-purchase.

valid_voucher_promo_code: >

  If you enter a promo code here, customers (but not box office staff) 
  will have to enter it in order to purchase this type of ticket for 
  this show.  You can associated multiple promo codes with the same
  offer, since their sales are reported separately.

valid_voucher_sales_dates: >

  The start and end sales times apply to customer self-purchase only.
  Box office staff can start selling before the "Start sales" time
  and can continue selling beyond the "End sales" time and even
  after the performance has started.

# Donations

donation_search_by_letter_sent: >

  When viewing donations, you can mark off all the ones for which you
  have sent an acknowledgment letter.  Checking this box restricts your
  search to donations not yet acknowledged, making it easy to export a
  list of all the donation letters you have to send.

# Reports

sublists: >

  Sublists are named subsets of your master email list as maintained by
  Mailchimp or ConstantContact.  By saving the result of a report as a
  sublist, you can then send an email campaign to just those patrons.

# Box office

checkin: >

  Click a number in this column to "check in" that many people in the 
  customer's party as they arrive.  
  A highlighted number indicates people who have
  checked in.  
  Click the X to "un-check-in" everyone in that customer's party.

checkin_house_capacity: >

  This is the ACTUAL (physical) capacity of the house, not the max sales
  cap for this performance.  Advance Sales is the number of advance
  tickets actually sold; Walkup Sales is the number of walkup tickets
  sold; Available is the number of actual physical seats remaining.

boxoffice_manager_only: >

  Issuing this ticket type in this situation requires Box Office Manager
  privilege. 
