# Configuration settings common to ALL VENUES
# PLEASE BE CAREFUL WHEN EDITING THIS FILE. The number of spaces at the
# beginnings of lines is significant. Do not use tabs.

# Time zone in which all calculations are done and in which time is displayed

timezone: 'PST8PDT'

# where to get help
  
help_manual: http://www.audience1st.com/help/manual.html
help_link: <a href="mailto:help@audience1st.com">help@audience1st.com</a>

# Special seating needs or requests

voucher_comments:
 - Wheelchair (manual)
 - Wheelchair (electric/oversized)
 - Crutches
 - Walker
 - Cane
 - No Stairs
 - Requires Aisle - Left Side
 - Requires Aisle - Right Side
 - Near Restroom
 - Other (briefly describe:)

phplist_default_list_id: 8

# Who email appears to come from (IMPORTANT: on many ISP's, this must be 
#  a valid deliverable username)
boxoffice_daemon_address: boxofficedaemon@audience1st.com

# Whom to contact for general application error
bug_notify:  armandofox@gmail.com

# Payment information

# IP addresses from which Walkup Sale page can be accessed w/o authentication
# separate with commas.  Not a good idea to rely on this in presence of DHCP.

walkup_locations: 127.0.0.1

# Number of DAYS OLD an inactive session must be before it's reaped

session_reap: 1

# name of button used for CC purchase - used for commit logic in some places
# to determine if 'pay by CC' or 'pay cash/check' was selected

cc_purch: "Credit Card Payment"

# Confirmation dialogs.  Trailing digit is # of string args expected.

messages:
  terms_of_sale_0: "Terms of use:\n\nI certify that I am 18 or over, or that I have the permission of a parent or adult guardian to provide the information required to complete this sale.\n\nI understand that ticket sales are final: No refunds or exchanges are allowed."
  areyousure_0: "Are you sure?"
  delete_user_2: "Delete customer %s %s? Perhaps you should consider merging the customer with another customer instead, or merging with WALKUP CUSTOMER to permanently deactivate this customer.  If you click OK, this customer's vouchers will be destroyed, which affects show reservation counts and will screw up referential integrity. This action cannot be undone, and it's probably not what you want.  If you are wise, click Cancel to back out now."
  remove_bundle_0: "OK to remove this voucher from customer account? This will NOT remove the individual vouchers that were part of the bundle - you have to remove those separately."
  remove_voucher_0: "OK to remove this voucher from customer account?"
  cancel_prepaid_0: "OK to cancel this revenue reservation?  NOTE: If this reservation was paid for with a credit card, cancellation WILL NOT cause the charge to be refunded.  Click OK to go ahead and cancel the reservation.  Click CANCEL to leave things as they are."
  delete_performance_0: 'Delete this performance: are you sure?'
  release_reservation_0: 'Really release this reservation? Click OK to release it, or Cancel to leave things as they are.'
  remove_vouchertype_1: 'This will destroy all existing "%s" vouchers, removing them from customer accounts. This action cannot be undone. Continue?'


# the underscored version of gateway_type's value will be used to derive the 
# _account  names, eg PayPal => pay_pal_account

gateway_type: AuthorizedNet

authorized_net_account:
  username: alamedalit1713
  password: 535HE3h837tD4wgp
  testing: false
  pemfile:

authorized_net_test_account:
  username: 33XUqKRw96
  password: 3GxPg8bh9ar358RA
  testing: true
  pemfile:

authorized_net_cp_account:
  username: 66Fx8Nue5
  password: 2HX5f5563f9XfS7J
  testing: false
  pemfile:
                                    
